version: 2
updates:
  # Root package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'discuno/maintainers'
    assignees:
      - 'discuno/maintainers'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier'
          - '@typescript-eslint/*'
          - 'typescript'
          - 'turbo'
        update-types:
          - 'minor'
          - 'patch'

  # Web app dependencies
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'discuno/maintainers'
    assignees:
      - 'discuno/maintainers'
    commit-message:
      prefix: 'chore(web)'
      include: 'scope'
    groups:
      react-ecosystem:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - 'next'
        update-types:
          - 'minor'
          - 'patch'
      ui-components:
        patterns:
          - '@radix-ui/*'
          - 'lucide-react'
          - 'tailwind*'
          - 'class-variance-authority'
          - 'clsx'
        update-types:
          - 'minor'
          - 'patch'

  # Atoms package dependencies
  - package-ecosystem: 'npm'
    directory: '/packages/discuno-atoms'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'discuno/maintainers'
    assignees:
      - 'discuno/maintainers'
    commit-message:
      prefix: 'chore(atoms)'
      include: 'scope'
    groups:
      ui-dependencies:
        patterns:
          - '@radix-ui/*'
          - 'lucide-react'
          - 'class-variance-authority'
          - 'clsx'
          - 'tailwind-merge'
        update-types:
          - 'minor'
          - 'patch'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'discuno/maintainers'
    assignees:
      - 'discuno/maintainers'
    commit-message:
      prefix: 'chore(ci)'
      include: 'scope'
