# GitHub Sponsors funding file
# These are supported funding model platforms

# GitHub Sponsors (preferred)
github: [discuno]

# Open Collective
open_collective: discuno

# Ko-fi
ko_fi: discuno

# Patreon
patreon: discuno

# Custom funding URLs
custom: ['https://discuno.com/sponsor', 'https://buymeacoffee.com/discuno']

# Liberapay
liberapay: discuno

# IssueHunt
issuehunt: discuno
